#create a .evn file in the same folder as this file and change the variables.
# MOUNT_POINT=/tmp/
# VPN_PROVIDER=changeme
# VPN_CONFIG=changeme
# VPN_USERNAME=changeme
# VPN_PASSWORD=changeme
#
#
version: "3.2"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MOUNT_POINT}/config/portainer:/data
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      TZ: ${TZ}
      WEBPASSWORD: Password
    # Volumes store your data between container upgrades
    volumes:
       - ${MOUNT_POINT}/config/pihole/etc/:/etc/pihole/
       - ${MOUNT_POINT}/config/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    
    restart: always
  transmission:
    container_name: transmission
    volumes:
      - '~/mediabox/transmission:/data'
      - '/etc/localtime:/etc/localtime:ro'
    cap_add:
      - NET_ADMIN
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=PROTONVPN
      - OPENVPN_CONFIG=CA\
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/16
    ports:
      - 9091:9091 # Transmission
      - 7878:7878
      - 9117:9117 # Jackett
      - 8989:8989
    image: 'haugene/transmission-openvpn:latest-armhf'
    restart: unless-stopped
    #  zerotier:
    #    image: croc/zerotier
    #    environment:
    #      - NETWORK_ID=d3ecf5726d18ad18
    ##      - ROUTES=10.10.12.0/23,10.147.20.115;10.10.14.0/23,10.147.20.220
    #    # volumes:
    #      # - './config/route.list:/config/route.list:ro'
    #    networks:
    #      - plexnet
    #    privileged: true
    #    restart: always
    #  organizr:
    #    image: linuxserver/organizr
    #    container_name: organizr
    #    environment:
    #      - PUID=1000
    #      - PGID=1000
    #      - TZ=${TZ}
    #    volumes:
    #      - ${MOUNT_POINT}/organizer-config:/config:cached
    #    ports:
    #      - 9983:80
    #    networks:
    #      - plexnet
    #    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    network_mode: service:transmission
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    volumes:
      - ${MOUNT_POINT}/transmission:/data:cached
      - ${MOUNT_POINT}/radarr-config:/config:cached
      - ${MOUNT_POINT}/transmission/completed:/downloads:cached
      - ${MOUNT_POINT}/media/movies:/movies:cached
    restart: always
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    network_mode: service:transmission
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    volumes:
      - ${MOUNT_POINT}/jackett/config:/config
      - ${MOUNT_POINT}/jackett/downloads:/downloads
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    network_mode: service:transmission
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    volumes:
      - ${MOUNT_POINT}/sonarr/config:/config:cached
      - ${MOUNT_POINT}/media/tv:/tv:cached
      - ${MOUNT_POINT}/transmission/completed:/downloads:cached
      - ${MOUNT_POINT}/transmission:/data:cached
    restart: unless-stopped
    #  emby:
    #    image: emby/embyserver
    #    container_name: emby
    #    networks:
    #      - plexnet
    #    environment:
    #      - UID=1000
    #      - GID=100
    #      - GIDLIST=100,44
    #    # devices:
    #      # - /dev/dri/renderD128
    #    volumes:
    #      - ${MOUNT_POINT}/emby/config:/config:cached
    #      - ${MOUNT_POINT}/media/movies:/movies:cached
    #      - ${MOUNT_POINT}/media/tv:/tv:cached
    #    ports:
    #      - 8096:8096
    #      - 8920:8920
    #    restart: unless-stopped
    #  bazarr:
    #    image: linuxserver/bazarr
    #    container_name: bazarr
    #    environment:
    #      - PUID=1001
    #      - PGID=1001
    #      - TZ=${TZ}
    #    networks:
    #      - plexnet
    #    volumes:
    #      - ${MOUNT_POINT}/bazarr/config:/config:cached
    #      - ${MOUNT_POINT}/media/movies:/movies:cached
    #      - ${MOUNT_POINT}/media/tv:/tv:cached
    #    ports:
    #      - 6767:6767
    #    deploy:
    #      resources:
    #        limits:
    #          memory: 4096M
    #    restart: unless-stopped
    #  daapd:
    #    image: linuxserver/daapd
    #    container_name: daapd
    #    network_mode: host
    #    environment:
    #      - PUID=1000
    #      - PGID=1000
    #      - TZ=${TZ}
    #    volumes:
    #      - ${MOUNT_POINT}/config/daapd:/config:cached
    #      - ${MOUNT_POINT}/media/music:/music:cached
    #    restart: unless-stopped
networks:
  plexnet:
    driver: bridge
