#create a .evn file in the same folder as this file and change the variables.
# MOUNT_POINT=/tmp/
# VPN_PROVIDER=changeme
# VPN_CONFIG=changeme
# VPN_USERNAME=changeme
# VPN_PASSWORD=changeme
#
#
version: "3"

services:
  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: always
    privileged: true
    ports:
      - "9091:9091"
    networks:
      - plexnet
    environment:
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - LOCAL_NETWORK=10.118.1.0/24
      - TZ=${TZ}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - TRANSMISSION_WEB_UI=kettu
      - TRANSMISSION_UMASK=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=0.001
      - TRANSMISSION_SPEED_LIMIT_UP=20
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
    volumes:
      - ${MOUNT_POINT}/transmission:/data:delegated
    restart: unless-stopped
  organizr:
    image: linuxserver/organizr
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${MOUNT_POINT}/organizer-config:/config:cached
    ports:
      - 9983:80
    networks:
      - plexnet
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    volumes:
      - ${MOUNT_POINT}/transmission:/data:cached
      - ${MOUNT_POINT}/radarr-config:/config:cached
      - ${MOUNT_POINT}/transmission/completed:/downloads:cached
      - ${MOUNT_POINT}/media/movies:/movies:cached
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    volumes:
      - ${MOUNT_POINT}/sonarr/config:/config:cached
      - ${MOUNT_POINT}/media/tv:/tv:cached
      - ${MOUNT_POINT}/transmission/completed:/downloads:cached
      - ${MOUNT_POINT}/transmission:/data:cached
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    networks:
      - plexnet
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
    volumes:
      - ${MOUNT_POINT}/jackett/config:/config:cached
      - ${MOUNT_POINT}/jackett/downloads:/downloads:cached
    ports:
      - "9117:9117"
    restart: unless-stopped
  emby:
    image: emby/embyserver
    environment:
      - UID=1000
      - GID=100
      - GIDLIST=100,44
    # devices:
      # - /dev/dri/renderD128
    volumes:
      - ${MOUNT_POINT}/emby/config:/config:cached
      - ${MOUNT_POINT}/media/movies:/movies:cached
      - ${MOUNT_POINT}/media/tv:/tv:cached
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=${TZ}
    networks:
      - plexnet
    volumes:
      - ${MOUNT_POINT}/bazarr/config:/config:cached
      - ${MOUNT_POINT}/media/movies:/movies:cached
      - ${MOUNT_POINT}/media/tv:/tv:cached
    ports:
      - 6767:6767
    deploy:
      resources:
        limits:
          memory: 4096M
    restart: unless-stopped
networks:
  plexnet:
    driver: bridge
